use std::time::Duration;

pub const REST_BASE: &str = "https://mainnet.zklighter.elliot.ai/api/v1";
pub const WS_BASE: &str = "wss://mainnet.zklighter.elliot.ai/stream?readonly=true";
pub const LIGHTER_EXCHANGE: &str = "lighter";
pub const GATE_EXCHANGE: &str = "gate";
pub const GATE_REST_BASE: &str = "https://api.gateio.ws/api/v4";
pub const GATE_WS_BASE: &str = "wss://fx-ws.gateio.ws/v4/ws/usdt";
pub const TARGET_SUBSCRIPTIONS_PER_CONNECTION: usize = 80;
pub const SNAPSHOT_REFRESH_INTERVAL: Duration = Duration::from_secs(24 * 60 * 60);
pub const MARKET_STATS_CHANNEL: &str = "market_stats/all";
pub const WEB_BIND_ADDR: &str = "0.0.0.0:3000";
pub const DATABASE_PATH: &str = "data/lighter.db";
pub const DEFAULT_WINDOW_HOURS: f64 = 1.0;
pub const DEFAULT_PRICE_JUMP_THRESHOLD_PCT: f64 = 2.0;
pub const DEFAULT_OPEN_INTEREST_THRESHOLD: f64 = 500_000.0;
pub const DEFAULT_SPREAD_THRESHOLD_PCT: f64 = 0.05;
pub const DEFAULT_MAX_HOLD_MINUTES: f64 = 0.0;
pub const DEFAULT_SIM_ORDER_QUOTE_SIZE: f64 = 100.0;
pub const DEFAULT_SIM_TAKE_PROFIT_PCT: f64 = 0.1;
pub const DEFAULT_SIM_TAKE_PROFIT_RATIO_PCT: f64 = 100.0;
pub const DEFAULT_SIM_TAKE_PROFIT_PCT_2: f64 = 0.0;
pub const DEFAULT_SIM_TAKE_PROFIT_RATIO_PCT_2: f64 = 0.0;
pub const DEFAULT_SIM_STOP_LOSS_PCT: f64 = 0.0;
pub const DEFAULT_LIVE_TRADING_ALLOW_OPENS: bool = true;
pub const DEFAULT_LIVE_OPEN_COOLDOWN_SECONDS: f64 = 0.0;
pub const DEFAULT_LIVE_MAX_ORDER_QUOTE_NOTIONAL: f64 = 0.0;
pub const DEFAULT_LIVE_MAX_SYMBOL_EXPOSURE_QUOTE_NOTIONAL: f64 = 0.0;
pub const DEPTH_SAMPLE_WINDOW: usize = 14;
pub const MAX_SIGNAL_HISTORY: usize = 200;
pub const MAX_ORDER_HISTORY: usize = 200;
pub const LATENCY_SAMPLE_WINDOW: usize = 4096;
pub const READ_MODEL_REFRESH_INTERVAL: Duration = Duration::from_millis(200);
pub const PERSISTENCE_BATCH_SIZE: usize = 64;
pub const EVENT_BATCH_SIZE: usize = 128;
